#!/usr/bin/env bash

set -x
set -e

echo "|> prepare env"
export HOME=/home/neon
export PROJECT=$HOME/Projects/Go/src/github.com/tapglue/snaas
export REVISION=$(git rev-parse --short HEAD)
#source ~/.gimme/envs/go1.7.5.env

CIRCLE_BUILD_NUM=1

echo "|> build gateway-http"
sudo docker run \
	-e GODEBUG=netdns=go \
	--rm \
	-v $HOME/Projects/Go:/go \
	-w /go/src/github.com/tapglue/snaas \
	golang:1.8.0-alpine \
	sh -c "go build \
		-ldflags \"-X main.revision=${REVISION}\" \
		-o gateway-http_${CIRCLE_BUILD_NUM} \
		cmd/gateway-http/*.go"

echo "|> build sims"
sudo docker run \
	-e GODEBUG=netdns=go \
	--rm \
	-v $HOME/Projects/Go:/go \
	-w /go/src/github.com/tapglue/snaas \
	golang:1.8.0-alpine \
	sh -c "go build \
		-ldflags \"-X main.revision=${REVISION}\" \
		-o sims_${CIRCLE_BUILD_NUM} \
		cmd/sims/*.go"

echo "|> build container"
sudo docker build \
	-f ${PROJECT}/infrastructure/docker/snaas.docker \
    -t tapglue/snaas:${CIRCLE_BUILD_NUM} \
    --build-arg GATEWAY_HTTP_BINARY=gateway-http_${CIRCLE_BUILD_NUM} \
    --build-arg SIMS_BINARY=sims_${CIRCLE_BUILD_NUM} \
    ${PROJECT}
